version: "3.8"

services:

  # The back-end database used by Bubbly and Grafana
  postgres:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "bubbly"
    networks:
      - bubbly-net
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"

  # Grafana with GraphQL plugin
  grafana:
    depends_on: 
      - "postgres"
    image: grafana/grafana:7.3.7
    networks:
      - bubbly-net
    environment: 
      GF_INSTALL_PLUGINS: "fifemon-graphql-datasource"
    ports:
      - "3000:3000"

  # TODO delay starting Bubbly server until Postgres is set up

  # Bubbly server
  bubbly:
    depends_on: 
      - "postgres"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bubbly-net
    ports:
      - "8111:8111"
    command:
      - "server"
      - "--debug"

# User-defined bridge network is different from the default bridge
networks:
  bubbly-net:
    driver: bridge
    internal: false
