---
apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: verifa/bubbly
deploy:
  kubeContext: kind-bubbly
  kubectl:
    manifests:
      # apply the nginx-ingress controller
      - https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
      # apply postgres
      - ./kubernetes/postgres-configmap.yaml
      - ./kubernetes/postgres.yaml
      # apply bubbly
      - ./kubernetes/bubbly-configmap.yaml
      - ./kubernetes/bubbly.yaml

profiles:
  # - name: development
  #   activation:
  #     - command: dev
  #     - command: run
  #   patches:
  #     - op: add
  #       path: /deploy/kubectl/manifests/-
  #       value: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
  - name: integration
    # profile for integration testing
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: verifa/bubbly-integration
          docker:
            target: integration
      - op: add
        path: /deploy/kubectl/manifests/-
        value: ./kubernetes/bubbly-integration.yaml
