---
apiVersion: batch/v1
kind: Job
metadata:
  name: bubbly-integration
spec:
  template:
    metadata:
      labels:
        type: bubbly-integration
    spec:
      initContainers:
        - name: init-db
          image: postgres:13.0
          command:
            [
              "sh",
              "-c",
              "until pg_isready -h postgres -p 5432;  do echo waiting for database; sleep 2; done;",
            ]
        - name: init-bubbly
          image: busybox:1.33
          command:
            [
              "sh",
              "-c",
              "until nc -zv bubbly 8111; do echo waiting for bubbly; sleep 1; done",
            ]
      containers:
        - name: bubbly-integration
          image: verifa/bubbly-integration
          envFrom:
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: bubbly-config
      restartPolicy: Never
  backoffLimit: 0
