## workflow for running integration tests

on:
  # run on a pull request to any branch
  pull_request:
    branches:
      - "**"

name: integration
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: cache go mod
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Create k8s Kind Cluster
        # Skip job if testing action locally using act
        if: ${{ !env.ACT }}
        uses: helm/kind-action@v1.1.0
        with:
          cluster_name: "bubbly"
          config: "kind-config.yaml"
      - name: Install skaffold
        uses: daisaru11/setup-cd-tools@v1
        env:
          # allow unsecure commands like ::add-path:: because this action uses it...
          # https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          skaffold: "1.17.1"
      - name: Build and deploy to cluster
        run: skaffold run -p integration
      - name: Integration test logs
        run: |
          # print the logs and follow until complete
          kubectl logs --follow --tail=-1 --selector job-name=bubbly-integration
          # check if the job succeedded
          JOB_SUCCESS=$(kubectl get job bubbly-integration -o jsonpath='{.status.succeeded}')
          # check the result and exit if failed
          if [ "$JOB_SUCCESS" != "1" ]; then exit 1; fi
          echo "Integration tests finished successfully!"
