## workflow for running integration tests

on:
  # run this workflow on master branch or a PR
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

name: integration
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: cache go mod
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Integration tests
        run: |
          docker-compose up -d cockroachdb
          # just sleep a bit to wait for the containers to start
          sleep 1
          docker-compose up -d bubbly
          sleep 1

          docker-compose logs
          go test ./... -tags=integration -count=1
